### ISSUE TITLE
 Index Error: uninformative error

### ISSUE THREAD

**Issue by NorAlnaami** [uuinfolab/py_multinet#2]
When the number of attributes differ from number of values, an uinformative error such as the following is given:
`net = ml.read(main_path+"/data/"+dataset_name+"/"+dataset_name+"_graph.txt") IndexError: vector::_M_range_check: __n (which is 76) >= this->size() (which is 76)`

This error does not indicate for which attribute a value is not provided.

**Comment by NorAlnaami** [comment]
[rice_graph.txt](https://github.com/uuinfolab/py_multinet/files/9400190/rice_graph.txt)

**Comment by magnanim** [comment]
Added a meaningful error message - for the provided example, it prints:

`Format error: [line 18] actor1 name, actor2 name and layer name expected`

(Development branch)
