### ISSUE TITLE
 Runtime Error: no support for undefined or NaN values

### ISSUE THREAD

**Issue by NorAlnaami** [uuinfolab/py_multinet#3]
The following error message when variable in the dataset are undefined:

```
    net = ml.read(main_path+"/data/"+dataset_name+"/"+dataset_name+"_graph.txt")
RuntimeError: Format error: Error converting string to double: NaN
```

**Comment by magnanim** [comment]
Do you have an input file to replicate it?

**Comment by magnanim** [comment]
I pushed an extension to development. This feature should have been added, I tried it on an input file with NULL specified where values are missing and I could retrieved None in Python.
