### ISSUE TITLE
AttributeError: module 'uunet.multinet' has no attribute 'read'

### ISSUE THREAD

**Issue by YuhangWang-Fishtank** [uuinfolab/py_multinet#4]
When I tried the tutorial, I encountered the error “AttributeError: module 'uunet.multinet' has no attribute 'read'”.

I wonder if I need to import the "main.cpp" in "C++" files, because my "ext" folder is all empty, and I can't find any function named "read" in "multinet.py"(although it try import read function in multinet.py). 

I know nothing about C. If I need to work with cpp files, can you provide a link to a relevant tutorial。

Thank you!

**Comment by magnanim** [comment]
Hi, can you send (1) the result of the installation (done with pip?) and (2) the code that generated the error? Thanks.

**Comment by YuhangWang-Fishtank** [comment]
I have no idea. My error is gone, but I don't know how it disappear. I think it may out of confilt of diffrerent envirnoment?

**Comment by YuhangWang-Fishtank** [comment]
> 

Thank you for your work. I don't have a problem for now, but I think someone might still have this problem.

**Comment by Topology121** [comment]
I have the same error!
![capture_20230120201524177](https://user-images.githubusercontent.com/77572648/213693765-9b24dc35-f05b-48a6-b9b2-29ae1370479d.jpG)

**Comment by magnanim** [comment]
Hi, I cannot replicate the error. Can you show the output of the installation, or provide details on how your system has been set up?

**Comment by Topology121** [comment]
Hi, I’m so glad to receive your reply!!!! Since I deleted the wrong code, I can't provide you detailed information.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Matteo ***@***.***>
发送时间: 2023年1月23日 5:33
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [uuinfolab/py_multinet] AttributeError: module 'uunet.multinet' has no attribute 'read' (Issue #4)


Hi, I cannot replicate the error. Can you show the output of the installation, or provide details on how your system has been set up?

―

**Comment by magnanim** [comment]
I'd suggest to first check if the library can be installed correctly. For example, from command line:

`python -m pip install uunet`

The output should finish with something like:

`Installing collected packages: uunet
Successfully installed uunet-1.1.4`

So you can see if it works. On my system:

`python`
`>>> import uunet.multinet as ml`
`>>> ml.empty()`
`ml-net[0, 0, 0, 0 (0,0)]`

If there is a problem in the installation it should be visible here. If not, then the problem can be in the integration with the notebook.

**Comment by Topology121** [comment]
Thanks for your suggestions, I will try.Thanks you very very very very much!!!!!!!!!!!!!!

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Matteo ***@***.***>
发送时间: 2023年1月23日 15:32
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [uuinfolab/py_multinet] AttributeError: module 'uunet.multinet' has no attribute 'read' (Issue #4)


I'd suggest to first check if the library can be installed correctly. For example, from command line:

python -m pip install uunet

The output should finish with something like:

Installing collected packages: uunet Successfully installed uunet-1.1.4

So you can see if it works. On my system:

`python

import uunet.multinet as ml
ml.empty()
ml-net[0, 0, 0, 0 (0,0)]`

If there is a problem in the installation it should be visible here. If not, then the problem can be in the integration with the notebook.

―
