### ISSUE TITLE
Wrong size of graph read

### ISSUE THREAD

**Issue by NorAlnaami** [uuinfolab/py_multinet#5]
ml-net[100, 1, 100, 251 (251,0)]
When the file attached is loaded by uunet.multinet, it reads 100 nodes although there are only 50 nodes and 251 edges.
[generic_networks_graph_clus_50_6_06_3_7.txt](https://github.com/uuinfolab/py_multinet/files/10735213/generic_networks_graph_clus_50_6_06_3_7.txt)

**Comment by magnanim** [comment]
Fixed in version 2.0. Output with current version on PyPI (2.1.1):

```
>>> import uunet.multinet as mn
>>> mn.read("./generic_networks_graph_clus_50_6_06_3_7.txt")
ml-net[50, 1, 50, 251 (251,0)]
```
